name: ai_agrivision
description: "AI-AgriVision: Production-Oriented Smart Agriculture Crop Disease Detection & Advisory Mobile App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.1
  http_parser: ^4.1.2
  image_picker: ^1.1.2
  geolocator: ^12.0.0
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.1
  url_launcher: ^6.3.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
